# problem 2
'''Write a program to input eight numbers from the user and display all the unique numbers (once).'''
set=set()
number=input("Enter Number : ")
set.add(int(number))
number=input("Enter Number : ")
set.add(int(number))
number=input("Enter Number : ")
set.add(int(number))
number=input("Enter Number : ")
set.add(int(number))
number=input("Enter Number : ")
set.add(int(number))
number=input("Enter Number : ")
set.add(int(number))
number=input("Enter Number : ")
set.add(int(number))
number=input("Enter Number : ")
set.add(int(number))
print(set)